### ISSUE TITLE
Write API Documentation

### ISSUE THREAD

**Issue by zacowan** [swamphacks/serverless-api#6]
### Task
Before coding the API, write documentation outlining the various endpoints and data types. 
### Steps
- [ ] Write user API documentation (user CRUD)
- [ ] Write event API documentation (event CRUD)
- [ ] Write application API documentation (application CRUD)
### Reference
It's ultimately up to you how you want to write the documentation, but it is important and will help keep things structured in the future.
